Параметр chain для каждого запроса
gear-tech/gear-js pull request #127
Opened 2021-11-04 19:40 UTC by tragedyHub

Fixes # .

-
-
-

@reviewer-or-team

2021-11-04 19:44 UTC, codev0 approved these changes

2021-11-04 19:44 UTC, codev0 commented on website/frontend/src/api/initApi.ts
> +  private chain: any;
why `any`?

2021-11-05 04:38 UTC, osipov-mit requested changes

2021-11-05 04:38 UTC, osipov-mit commented on website/frontend/src/services/ServerRPCRequestService.ts
> +      chain: localStorage.getItem('chain'),
The chain parameter must be inside of params field

2021-11-05 04:38 UTC, osipov-mit commented on website/frontend/src/api/initApi.ts
> +    this.chain = this._api.chain().then((res) => localStorage.setItem('chain', res));
What will be the value of this.chain? Promise?

2021-11-05 12:38 UTC, osipov-mit approved these changes

2021-11-05 12:53 UTC, merged