Add ability `indexer` and `test-balance` services to reconnect and change provider address.
gear-tech/gear-js pull request #1279
Opened 2023-04-28 07:27 UTC by Almazatun

Resolves # .

- Add ability `indexer` and `test-balance` services to reconnect and change provider address if a network does not work.
- Add `retry` connection option for each provider address.
- Bump `@gear-js/api` package in services.

@reviewer-or-team

2023-04-28 08:12 UTC, osipov-mit requested changes

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +  const api = new GearApi({ providerAddress: providerAdd });
```suggestion
  if (!providerAddr) {
    throw new Error('some error');
  }
  const api = new GearApi({ providerAddress: providerAddr });
```

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +  connectionStatus && cb(RMQServiceActions.ADD, genesis);
```suggestion
  await indexer.run(api);
  cb(RMQServiceActions.ADD, genesis);
```

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +let connectionStatus;
```suggestion
let connectionStatus = false;
```

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +    connectionStatus = true;
no need
```suggestion

```

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +  if(connectionStatus) return;
```suggestion
  if (connectionStatus) return;
```

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +  for(let i = 0; i <= addresses.length; i + 1){
Pls try to set up linter
```suggestion
  for (let i = 0; i <= addresses.length; i + 1) {
```

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +    providerAdd = getProviderAddress(addresses);
```suggestion
    addresses = addresses.filter((address) => address !== providerAdd);
    providerAdd = addresses[0]
```

2023-04-28 08:12 UTC, osipov-mit commented on idea/indexer/src/gear/connect.ts
> +  }
How can it be possible that `connectionStatus` will be `true` here? I think it would be better to move this part to `connectToNode` function

2023-04-28 09:37 UTC, Almazatun commented on idea/indexer/src/common/helpers/get-provider-address.ts
> +}
Deleted helper func

2023-07-19 12:37 UTC, osipov-mit approved these changes

2023-07-19 12:37 UTC, merged