ny-idea-api
gear-tech/gear-js pull request #1502
Opened 2024-03-06 12:25 UTC by nikitayutanov

2024-03-11 10:13 UTC, faizov approved these changes

2024-03-11 10:26 UTC, YauheniDraichykau approved these changes

2024-03-12 14:00 UTC, osipov-mit requested changes

2024-03-12 14:00 UTC, osipov-mit commented on idea/frontend/src/api/metadata/requests.ts
> +const addMetadata = (hash: HexString) => rpcService.callRPC(RpcMethods.AddMetadata, { hash });
`hex` should be sent as before

2024-03-13 13:48 UTC, merged