update envs and deps
gear-tech/gear-js pull request #225
Opened 2021-12-20 19:49 UTC by codev0

- update 
- move dev dependencies to proper place

2021-12-21 08:18 UTC, osipov-mit requested changes

2021-12-21 08:18 UTC, osipov-mit commented on website/frontend/package.json
> +    "@gear-js/api": "^0.8.17",
```suggestion
    "@gear-js/api": "^0.8.18",
```

2022-01-04 15:14 UTC, osipov-mit approved these changes

2022-01-05 08:21 UTC, EugenWay approved these changes

2022-01-05 08:43 UTC, merged