Change upload page template
gear-tech/gear-js pull request #287
Opened 2022-01-24 05:37 UTC by aderrod94

2022-02-02 09:21 UTC, nikitayutanov commented on website/frontend/src/store/reducers/AlertReducer.ts
> +
I guess there's something wrong

2022-02-02 09:21 UTC, nikitayutanov commented on website/frontend/src/services/ApiService.tsx
> +  console.log(meta);
Should it remain?

2022-02-02 09:21 UTC, nikitayutanov commented on website/frontend/src/helpers.ts
> +};
You specified type as File, yet checking its existence

2022-02-02 09:21 UTC, nikitayutanov commented on website/frontend/src/components/blocks/UploadForm/children/MetaFile/MetaFile.tsx
> +  const metaFieldRef = useRef<HTMLDivElement | null>(null);
```suggestion
  const metaFieldRef = useRef<HTMLDivElement>(null);
```

You can omit `| null` since it's read only ref

2022-02-02 09:21 UTC, nikitayutanov commented on website/frontend/src/components/blocks/UploadForm/children/MetaFields/MetaField/MetaField.tsx
> +  touched: any;
Can we specify types?

2022-02-02 09:21 UTC, nikitayutanov commented on website/frontend/src/components/blocks/UploadForm/children/MetaFields/MetaFields.tsx
> +  touched: any;
Can we specify types?

2022-02-02 09:21 UTC, nikitayutanov commented on website/frontend/src/consts.ts
> +];
I believe it's better to define it locally. Or to do it using enum so we'd have the ability to reuse names across other components.

2022-02-02 14:13 UTC, osipov-mit requested changes

2022-02-02 14:13 UTC, osipov-mit commented on website/frontend/src/components/blocks/UploadForm/UploadForm.tsx
> +        const inputType = getTypeStructure(metaWasm?.handle_input, displayedTypes);
Why do you use `handle_input` type here?

2022-02-03 10:29 UTC, osipov-mit approved these changes

2022-02-17 16:12 UTC, osipov-mit requested changes

2022-02-21 09:56 UTC, osipov-mit approved these changes

2022-02-21 10:29 UTC, merged