resolve metaform issues
gear-tech/gear-js pull request #316
Opened 2022-01-31 19:11 UTC by codev0

- fix field with null meta form issues

2022-04-06 09:52 UTC, nikitayutanov commented on website/frontend/.eslintrc
> +  "plugins": ["import"],
Why?

2022-04-06 09:52 UTC, nikitayutanov commented on website/frontend/package.json
>    },
Doesn't `eslintConfig` in the `package.json` gets overridden by `.eslintrc`?

2022-04-06 09:52 UTC, nikitayutanov commented on website/frontend/.storybook/main.js
> +    builder: 'webpack5',
Why `webpack 5` over default `@storybook/builder-webpack5`?

2022-04-06 11:07 UTC, codev0 commented on website/frontend/.eslintrc
> +  "plugins": ["import"],
restored

2022-04-06 11:50 UTC, nikitayutanov commented
Main goal is to improve code readibility and quality.

Some quick observations:
- Decomposite large components and functions into smaller ones, organize them, etc
- Create functions/variables for constantly repeating ones
- Inner `__*varName*` variables should be incapsulated
- Tests: stick to naming conventions, orginize them

Something to think of:
- Metaform name and names of inner variables based on it. Is it really `MetaForm` and not `PayloadForm` or something?

2022-04-19 10:09 UTC, osipov-mit requested changes

2022-04-19 10:09 UTC, osipov-mit commented on .github/workflows/CI-build-website.yml
> +          yarn install --immutable
Why is it needed? yarn install runs with this flag on CI anyway

2022-04-19 10:49 UTC, nikitayutanov commented on website/frontend/package.json
> +    "webpack": "5.70.0"
No need for explicit webpack declaration

2022-04-19 17:07 UTC, osipov-mit approved these changes

2022-04-19 17:09 UTC, merged