Az rpc handler
gear-tech/gear-js pull request #34
Opened 2021-09-25 21:25 UTC by codev0

Fixes # .

- add RPC handler
- create AppContext with RPC call class instances
- move blocks subscription to its component

@reviewer-or-team

2021-09-26 05:12 UTC, osipov-mit requested changes

2021-09-26 05:12 UTC, osipov-mit commented on website/frontend/src/consts.ts
> +  READ_EVENTS: 'events.read',
The method doesn't exist

2021-09-28 08:45 UTC, EugenWay commented
Please, merge master with last fix

2021-09-28 09:15 UTC, EugenWay requested changes
Please, merge master with the last fix

2021-09-28 09:58 UTC, 0ashen approved these changes

2021-09-28 10:04 UTC, EugenWay approved these changes

2021-09-28 10:20 UTC, osipov-mit approved these changes

2021-09-28 13:20 UTC, merged