add: prettier pre-commit
gear-tech/gear-js pull request #49
Opened 2021-09-28 13:40 UTC by osipov-mit

2021-09-28 13:42 UTC, EugenWay approved these changes

2021-09-28 14:15 UTC, codev0 requested changes

2021-09-28 14:15 UTC, codev0 commented on package.json
> +    "*.{js,css,md,ts,tsx}": "prettier --write"
add scss pls

2021-09-28 14:16 UTC, osipov-mit commented on package.json
> +    "*.{js,css,md,ts,tsx}": "prettier --write"
done

2021-09-29 07:54 UTC, osipov-mit commented
@codev0 resolved?

2021-09-29 13:49 UTC, codev0 approved these changes

2021-09-29 15:19 UTC, merged