Display reason of InitFailure
gear-tech/gear-js pull request #608
Opened 2022-04-24 12:25 UTC by aderrod94

2022-04-24 12:39 UTC, osipov-mit requested changes

2022-04-24 12:39 UTC, osipov-mit commented on website/frontend/src/services/ApiService.tsx
> +      const message = `${method}: \n ${description}`;
I think it's better to display programId in any case.
And display `asDispatch` if `reason?.isDispatched` will be true

2022-04-25 16:13 UTC, Pinkdesu reviewed
`if(info.origin.toHex() !== filterKey) return`

`const isInitFailure = method === EVENT_TYPES.PROGRAM_INITIALIZATION_FAILURE;`
`const reasonOfInitFailure = reason?.isDispatch && reason?.asDispatch.toHuman();`

`const message =  reasonOfInitFailure &&  isInitFailure ? `${method}: ${reasonOfInitFailure}\n ${info.programId.toHex()}`  :  `${method}\n ${info.programId.toHex()};`

`const showAlert = reason ? alert.error : alert.success;`

`showAlert(message);`

2022-04-25 20:28 UTC, nikitayutanov commented on website/frontend/src/services/ApiService.tsx
> +          : `${method}\n ${programId}`;
```suggestion
      const isInitFailure = method === EVENT_TYPES.PROGRAM_INITIALIZATION_FAILURE;
      const initFailureReason = reason?.isDispatch && reason?.asDispatch.toHuman();
      const programId = info.programId.toHex();

      const methodString = initFailureReason && isInitFailure ? `${method}: ${initFailureReason}` : `${method}`;
      const message = `${methodString}\n${programId}`;
```

2022-04-26 07:49 UTC, Pinkdesu approved these changes

2022-04-26 07:55 UTC, nikitayutanov approved these changes

2022-04-26 10:38 UTC, osipov-mit approved these changes

2022-04-26 10:39 UTC, merged