Az connect events subscription
gear-tech/gear-js pull request #66
Opened 2021-10-05 18:04 UTC by codev0

Fixes # .

- fix typos and docs in api
- add events subscriptions

@reviewer-or-team

2021-10-06 04:45 UTC, osipov-mit requested changes

2021-10-06 04:45 UTC, osipov-mit commented on api/package.json
> -  "version": "0.4.5",
Why did you downgrade the version?

2021-10-06 05:32 UTC, osipov-mit approved these changes

2021-10-07 09:04 UTC, osipov-mit commented on website/frontend/src/store/actions/actions.ts
> +    event.data.forEach((i) => {
```javascript
import {  InitSuccessData } from '@gear-js/api'
event.data.forEach((data: InitSuccessData) => {
  if (data.origin.toHex() === localStorage.getItem('public_key_raw')){
    // to do smth
}
})

```

2021-10-07 09:04 UTC, osipov-mit commented on website/frontend/src/store/actions/actions.ts
> +      if (data.source === localStorage.getItem('public_key_raw')) {
`source` property is not exists here. you should use `origin`

2021-10-07 09:05 UTC, osipov-mit commented on website/frontend/src/store/actions/actions.ts
> +      if (data.source === localStorage.getItem('public_key_raw')) {
Here `source` means program id, and you should use `dest` property

2021-10-07 09:07 UTC, osipov-mit commented on website/frontend/src/store/actions/actions.ts
> +    event.data.forEach((i) => {
```javascript
import {  LogData } from '@gear-js/api'
event.data.forEach((data: LogData) => {
  if (data.dest.toHex() === localStorage.getItem('public_key_raw')){
    // to do smth
}
})
```

2021-10-07 09:09 UTC, osipov-mit commented on website/frontend/src/store/actions/actions.ts
> +  nodeApi.subscribeProgramEvents((event) => {
Here you need to check what event is (InitSuccess or InitFailure)

You can use
```javascript
nodeApi.subscribeProgramEvents(({ data, method }) => {
  // method is event name
  // to do stmh
})
```

2021-10-07 09:14 UTC, osipov-mit commented
@codev0 You should merge branch move-node-conn-to-front and install packages with updated @gear-js/api

2021-10-09 16:05 UTC, osipov-mit requested changes

2021-10-09 16:05 UTC, osipov-mit commented on website/frontend/src/store/actions/actions.ts
> +    data.forEach((eventData: LogData) => {
Here you should filter events and display only events for current account
```javascript
if (eventData.dest.toHex() === localStorage.getItem('public_key_raw')) 
```

2021-10-10 18:23 UTC, EugenWay approved these changes

2021-10-10 18:25 UTC, merged