Refactor message page
gear-tech/gear-js pull request #798
Opened 2022-07-05 14:07 UTC by Pinkdesu

- Refactored message page

2022-07-06 11:10 UTC, osipov-mit requested changes

2022-07-06 11:10 UTC, osipov-mit commented on website/frontend/src/tests/mocks/handlers/helpers.ts
> +    replyError: '1',
`replyError` doesn't exist in response from now on

2022-07-06 11:10 UTC, osipov-mit commented on website/frontend/src/types/message.ts
>    replyError: any;
as above

2022-07-07 09:57 UTC, aderrod94 commented on website/frontend/src/components/blocks/MessagesList/MessagesList.tsx
> +      {messages.map((message: MessageModel) => (
Better to use getMessages function that return result of the map

2022-07-07 09:59 UTC, aderrod94 commented on website/frontend/src/components/blocks/MessagesList/children/MessageItem/MessageItem.tsx
> +    <li className={clsx(styles.messageItem, exitCode ? styles.error : styles.success)}>
Store classes in the variable and use here

2022-07-07 14:04 UTC, Pinkdesu commented on website/frontend/src/components/common/CircleIndicator/CircleIndicator.tsx
> +  <span className={clsx(styles.circleIndicator, styles[status], className)} />
I don't see the point in this case.

2022-07-07 16:32 UTC, aderrod94 approved these changes

2022-07-08 12:29 UTC, osipov-mit approved these changes

2022-07-08 12:30 UTC, merged